---

- name: Set AppDynamics Machine Agent S3 Bucket
  set_fact:
    appd_machine_agent_s3_bucket: "{{ appd_machine_agent_rpm_url | regex_replace('^s3://((\\w+|\\-)*)\\/.*$', '\\1') }}"

- name: Set AppDynamics Machine Agent S3 Key
  set_fact:
    appd_machine_agent_s3_key: "{{ appd_machine_agent_rpm_url | regex_replace('^s3://[0-9a-zA-Z\\-]*\\/(.*)\\/.*$', '\\1') }}"

- name: Get AppDynamics Machine Agent RPM - S3
  aws_s3:
    bucket: "{{ appd_machine_agent_s3_bucket }}"
    object: "{{ appd_machine_agent_s3_key }}/{{ appd_machine_agent_rpm_name }}"
    dest: "/root/installers/{{ appd_machine_agent_rpm_name }}"
    mode: get

- name: AppDynamics Machine Agent Correct Ownership
  file: 
    path: "/root/installers/{{ appd_machine_agent_rpm_name }}"
    owner: root
    group: root
    mode: 0744
