---

- name: Get Kafka Package - Web
  get_url:
    url: "{{ kafka_package_url }}"
    validate_certs: no
    dest: "/root/installers/{{ kafka_archive_name }}"
    owner: root
    group: root
    mode: 0744