---

- name: Set AppDynamics AppServer Agent Url Base
  set_fact:
    appd_app_agent_zip_url: "{{ appd_app_server_agent_zip_url | regex_replace('^(.*)\\/.*$', '\\1') }}"

- name: Get AppDynamics AppServer Agent RPM - Web
  get_url:
    url: "{{ appd_machine_agent_rpm_url }}&wget=true"
    dest: "/root/installers/{{ appd_app_agent_archive_name }}"

- name: AppDynamics AppServer Agent Correct Ownership
  file: 
    path: "/root/installers/{{ appd_app_agent_archive_name }}"
    owner: root
    group: root
    mode: 0744
