---

- name: Set Sumologic S3 Bucket
  set_fact:
    sumologic_s3_bucket: "{{ sumologic_rpm_url | regex_replace('^s3://((\\w+|\\-)*)\\/.*$', '\\1') }}"

- name: Set Sumologic S3 Key
  set_fact:
    sumologic_s3_key: "{{ sumologic_rpm_url | regex_replace('^s3://[0-9a-zA-Z\\-]*\\/(.*)\\/.*$', '\\1') }}"

- name: Set Sumologic RPM Name
  set_fact:
    sumologic_rpm_name: "{{ sumologic_rpm_url | regex_replace('^.*\\/(.*)$', '\\1') }}"

- name: Get Sumlogic RPM - S3
  aws_s3:
    bucket: "{{ sumologic_s3_bucket }}"
    object: "{{ sumologic_s3_key }}/{{ sumologic_rpm_name }}"
    dest: "/root/installers/{{ sumologic_rpm_name }}"
    mode: get

- name: Correct Ownership
  file: 
    path: "/root/installers/{{ sumologic_rpm_name }}"
    owner: root
    group: root
    mode: 0744
