---

- name: Get Encrypted Param Store Value
  shell: >
    aws ssm get-parameter --name {{ item.value.value }} --with-decryption --query 'Parameter.Value' --output text
    --region {{ ansible_ec2_placement_region }}
  register: encrypted_param_store_query
  when: (item.value.param_store == "yes") and
        (item.value.encrypted == "yes")

- name: Get Plain Param Store Value
  shell: >
    aws ssm get-parameter --name {{ item.value.value }} --query 'Parameter.Value' --output text
    --region {{ ansible_ec2_placement_region }}
  register: plain_param_store_query
  when: (item.value.param_store == "yes") and
        (item.value.encrypted == "no")

- name: Write out Plain Param Store Value
  lineinfile:
    path: "{{ spring_props_file }}"
    line: "{{ item.value.prop_name }}={{ plain_param_store_query.stdout }}"
  when: (item.value.param_store == "yes") and
        (item.value.encrypted == "no")

- name: Write out Encrypted Param Store Value
  lineinfile:
    path: "{{ spring_props_file }}"
    line: "{{ item.value.prop_name }}={{ encrypted_param_store_query.stdout }}"
  when: (item.value.param_store == "yes") and
          (item.value.encrypted == "yes")

- name: Write out Passed Value
  lineinfile:
    path: "{{ spring_props_file }}"
    line: "{{ item.value.prop_name }}={{ item.value.value }}"
  when: item.value.param_store == "no"