---

- name: Get Ec2 MetaData
  ec2_metadata_facts:

- name: Set AWS Hostname Fact
  set_fact:
    aws_hostname: "aws-{{ host_purpose }}-{{ host_environment }}-{{ ansible_ec2_local_ipv4 | regex_replace('^(\\d+).(\\d+).(\\d+).(\\d+)$', '\\1_\\2_\\3_\\4') }}"

